name: Repository Events
on:
    push:
        branches: 
            - main
            - "feature/*" 
            - "feature/**"
        branches-ignore:
            - develop
        tags:
            - v1.*
            - "!v1.1.1"
        paths:
            - "**.js"
            - "!app.js"
    pull_request:
        types: [opened,assigned,reopened,synchronize]
        branches:
            - main
        paths:
            - "**.js"
    issues:
        types: [opened]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps: 
            - run: | 
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4
